@startuml
用户 -> 用户接口: 登录操作
用户 -> 用户接口: 磁盘初始化
用户 -> 用户接口: 文件操作
用户 <- 用户接口: 操作不存在
用户 -> 用户接口: 文件操作
用户接口 -> runtime: 拿到相应参数
runtime -> VFS : 调用相应接口
VFS -> FS: 调用相应接口
FS -> 磁盘: 转换为对磁盘的操作
用户接口 -> 用户: 响应
@enduml